# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ish_lib 0.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "ish_lib"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Piousbox"]
  s.date = "2016-05-03"
  s.description = "models and assets for piousbox.com"
  s.email = "piousbox@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ish_lib.gemspec",
    "lib/app/models/ability.rb",
    "lib/app/models/admin_user.rb",
    "lib/app/models/app_model2.rb",
    "lib/app/models/auth_token.rb",
    "lib/app/models/aux_model.rb",
    "lib/app/models/cities_user.rb",
    "lib/app/models/city.rb",
    "lib/app/models/country.rb",
    "lib/app/models/day.rb",
    "lib/app/models/decoded_auth_token.rb",
    "lib/app/models/event.rb",
    "lib/app/models/feature.rb",
    "lib/app/models/gallery.rb",
    "lib/app/models/manager.rb",
    "lib/app/models/manager_city.rb",
    "lib/app/models/manager_feature.rb",
    "lib/app/models/manager_gallery.rb",
    "lib/app/models/manager_newsitem.rb",
    "lib/app/models/manager_photo.rb",
    "lib/app/models/manager_report.rb",
    "lib/app/models/manager_site.rb",
    "lib/app/models/manager_tag.rb",
    "lib/app/models/manager_user.rb",
    "lib/app/models/manager_venue.rb",
    "lib/app/models/message.rb",
    "lib/app/models/newsitem.rb",
    "lib/app/models/nodeitem.rb",
    "lib/app/models/photo.rb",
    "lib/app/models/rate_me.rb",
    "lib/app/models/report.rb",
    "lib/app/models/review.rb",
    "lib/app/models/site.rb",
    "lib/app/models/tag.rb",
    "lib/app/models/user.rb",
    "lib/app/models/user_profile.rb",
    "lib/app/models/venue.rb",
    "lib/app/models/video.rb",
    "lib/app/models/welcome.rb",
    "lib/app/models/wikitravel_page.rb",
    "lib/ish_lib.rb",
    "lib/string.rb",
    "test/helper.rb",
    "test/test_ish_lib.rb"
  ]
  s.homepage = "http://github.com/piousbox/ish_lib"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "ish_lib, powering piousbox.com"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
  end
end

