# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ish_lib 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "ish_lib"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Piousbox"]
  s.date = "2016-05-01"
  s.description = "models and assets for piousbox.com"
  s.email = "piousbox@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "ish_lib.gemspec",
    "lib/ish_lib.rb",
    "test/helper.rb",
    "test/test_ish_lib.rb"
  ]
  s.homepage = "http://github.com/piousbox/ish_lib"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "ish_lib, powering piousbox.com"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, ["~> 3.5"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 4.2"])
    else
      s.add_dependency(%q<shoulda>, ["~> 3.5"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.11"])
      s.add_dependency(%q<mongoid>, ["~> 4.2"])
    end
  else
    s.add_dependency(%q<shoulda>, ["~> 3.5"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.11"])
    s.add_dependency(%q<mongoid>, ["~> 4.2"])
  end
end

