
development:
  adapter: mysql2
  database: showv_development
  username: root
  password: 
  timeout: 5000

test:
  adapter: mysql2
  database: showv_test
  username: root
  password:
  timeout: 5000

production:
  adapter: jdbcmysql
  database: showv_production
  username: root
  password:
  timeout: 5000
