# config/memcached.yml
defaults:
  client: Dalli::Client
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  namespace: yourappname
  benchmarking: false
  disabled: false
  debug: false
 
development:
  servers: 127.0.0.1:11211
  # Developers who have memcached installed on their local system should comment the following line
  # disabled: true
 
test:
  disabled: true
 
staging:
  servers:
    - 127.0.0.1:11211
 
production:
  servers:
    - 127.0.0.1:11211:11211